# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries
name: test

on: [push, pull_request]

jobs:
  test:
    name: ${{ matrix.platform }} ( ${{ matrix.python-version }})
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Set up conda ${{ matrix.python-version }}
        uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          activate-environment: test
          python-version: ${{ matrix.python-version }}
          channels: conda-forge
      - name: Conda info
        shell: bash -l {0}
        run: conda info
      - name: Install pocl
        if: runner.os == 'Linux'
        shell: bash -l {0}
        run: conda install -y pocl
      - name: Install dependencies
        shell: bash -l {0}
        run: |
          python --version
          conda install -y pyopencl
          python -m pip install --upgrade pip
          pip install setuptools wheel pytest pytest-cov pytest-benchmark
          pip install -e .
      - name: Test
        shell: bash -l {0}
        run: pytest -v --cov=./ --cov-report=xml
      - name: Coverage
        uses: codecov/codecov-action@v1

  # deploy:
  #   needs: [ubuntu-latest, mac-win]
  #   runs-on: ubuntu-latest
  #   if: contains(github.ref, 'tags')
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Set up Python
  #       uses: actions/setup-python@v1
  #       with:
  #         python-version: "3.x"
  #     - name: Install dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install -U setuptools setuptools_scm wheel twine
  #     - name: Build and publish
  #       env:
  #         TWINE_USERNAME: __token__
  #         TWINE_PASSWORD: ${{ secrets.TWINE_API_KEY }}
  #       run: |
  #         git tag
  #         python setup.py sdist bdist_wheel
  #         twine upload dist/*
